### PR TITLE
Change node16 for node20

### PR DESCRIPTION
**Pull request by jmalvarezf-lmes**
Hey! This action is very useful, so it would be great to have it based on node20.

### CODE REVIEW

**Comment by adambirds** [comment]
I'd be happy upgrade this to use node 20, but please reverse all the name changes if you want me to merge this, if not I will just copy the edits and create a new merge.

**Comment by strazto** [comment]
> but please reverse all the name changes if you want me to merge this, if not I will just copy the edits and create a new merge.

I dont think the OP cares enough to undo their changes, imo you can copy the edits like you said

**Comment by jmalvarezf-lmes** [comment]
I had to do the renames in order to be able to use it while we had communication. I thought I did that in another branch, but I was wrong. 
I'll be closing this as we are good with that for now, and I have no time to revert this and create again, and the change is so minimal that you can do it by your own, it does not add value at all.
Thank you!

**Comment by jmalvarezf-lmes** [comment]
Closing.

**Pull request closed without merging**
